_wandb:
    value:
        cli_version: 0.24.0
        e:
            i7afm0ypwl21k2dx95kiyxvyqmguhhvy:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Unknown
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /Users/eorakcioglu/Desktop/projects/udacity/genre_classification/outputs/2026-02-09/12-10-12/random_forest_config.yml
                    - --export_artifact
                    - export_artifact
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: random_forest/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "182642241536"
                executable: /opt/miniconda3/envs/mlflow-484df64d71fdfb8fbb5f48803452d41c922ae5e3/bin/python
                git:
                    commit: 31f527cef0cb86db17f8dd6b32269c9dcd0846a9
                    remote: https://github.com/EbruOrakcioglu/genre_classification.git
                host: NSN-EBRUO2.local
                memory:
                    total: "38654705664"
                os: macOS-26.2-x86_64-i386-64bit-Mach-O
                program: /Users/eorakcioglu/Desktop/projects/udacity/genre_classification/random_forest/run.py
                python: CPython 3.13.12
                root: /Users/eorakcioglu/Desktop/projects/udacity/genre_classification/random_forest
                startedAt: "2026-02-09T09:11:22.394818Z"
                writerId: i7afm0ypwl21k2dx95kiyxvyqmguhhvy
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-x86_64
