_wandb:
    value:
        cli_version: 0.24.0
        e:
            l8cesphs687r7guyqk5q5bvbcsnpmnha:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Unknown
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "182994710528"
                executable: /opt/miniconda3/envs/mlflow-cd65784bf8e7fffc45c3ae66d3b5f5d3b28be86d/bin/python3.13
                git:
                    commit: 31f527cef0cb86db17f8dd6b32269c9dcd0846a9
                    remote: https://github.com/EbruOrakcioglu/genre_classification.git
                host: NSN-EBRUO2.local
                memory:
                    total: "38654705664"
                os: macOS-26.2-x86_64-i386-64bit-Mach-O
                program: /opt/miniconda3/envs/mlflow-cd65784bf8e7fffc45c3ae66d3b5f5d3b28be86d/bin/pytest
                python: CPython 3.13.12
                root: /Users/eorakcioglu/Desktop/projects/udacity/genre_classification/check_data
                startedAt: "2026-02-09T09:14:19.438642Z"
                writerId: l8cesphs687r7guyqk5q5bvbcsnpmnha
        m: []
        python_version: 3.13.12
        t:
            "4": 3.13.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-x86_64
