_wandb:
    value:
        cli_version: 0.24.0
        e:
            f368oxz94q43ln3fdiy8x04lsat0belm:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Unknown
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                args:
                    - --input_artifact
                    - raw_data.parquet:latest
                    - --artifact_name
                    - preprocessed_data.csv
                    - --artifact_type
                    - preprocessed_data
                    - --artifact_description
                    - Data with preprocessing applied
                codePath: preprocess/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "182270332928"
                email: ebru95orakcioglu@gmail.com
                executable: /opt/miniconda3/envs/mlflow-0c0de061eeaefd8cf19694dcf7baac6a336c7f6b/bin/python
                git:
                    commit: 31f527cef0cb86db17f8dd6b32269c9dcd0846a9
                    remote: https://github.com/EbruOrakcioglu/genre_classification.git
                host: NSN-EBRUO2.local
                memory:
                    total: "38654705664"
                os: macOS-26.2-x86_64-i386-64bit-Mach-O
                program: /Users/eorakcioglu/Desktop/projects/udacity/genre_classification/preprocess/run.py
                python: CPython 3.13.12
                root: /Users/eorakcioglu/Desktop/projects/udacity/genre_classification/preprocess
                startedAt: "2026-02-09T09:08:42.592558Z"
                writerId: f368oxz94q43ln3fdiy8x04lsat0belm
        m: []
        python_version: 3.13.12
        t:
            "4": 3.13.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-x86_64
